# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-06-03 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birthday', models.DateField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('confirm_email', models.EmailField(max_length=254)),
                ('avatar', models.CharField(max_length=255)),
                ('hometown', models.CharField(max_length=255)),
                ('hobby', models.CharField(max_length=255)),
                ('favorite_animal', models.CharField(max_length=255)),
                ('favorite_color', models.CharField(max_length=255)),
                ('bio', models.TextField()),
            ],
        ),
    ]
