# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-06-06 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190604_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default='I am a nerd for love.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthday',
            field=models.DateField(default='1990-01-15', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='confirm_email',
            field=models.EmailField(default='dave@email.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='dave@email.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_animal',
            field=models.CharField(default='Gianni', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='favorite_color',
            field=models.CharField(default='Blue', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='Dave', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hobby',
            field=models.CharField(default='Buckets', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='hometown',
            field=models.CharField(default='Denver', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='McGarvey', max_length=255),
        ),
    ]
