# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-06-06 21:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190606_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default=datetime.datetime(2019, 6, 6, 21, 55, 44, 691686, tzinfo=utc), max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
